In [2]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier

In [3]:
path = "..\Dataset\API_Kaggle\weather_classification_data.csv"
df = pd.read_csv(path)
df

Temperature  Humidity  ...  Location  Weather Type
0             14.0        73  ...    inland         Rainy
1             39.0        96  ...    inland        Cloudy
2             30.0        64  ...  mountain         Sunny
3             38.0        83  ...   coastal         Sunny
4             27.0        74  ...  mountain         Rainy
...            ...       ...  ...       ...           ...
13195         10.0        74  ...  mountain         Rainy
13196         -1.0        76  ...   coastal         Snowy
13197         30.0        77  ...   coastal        Cloudy
13198          3.0        76  ...    inland         Snowy
13199         -5.0        38  ...  mountain         Rainy

[13200 rows x 11 columns]

In [4]:
new_names = {'Precipitation (%)': 'Precipitation',
             'Visibility (km)': 'Visibility',}
df.rename(columns=new_names, inplace=True)
df

Temperature  Humidity  Wind Speed  ...  Visibility  Location  Weather Type
0             14.0        73         9.5  ...         3.5    inland         Rainy
1             39.0        96         8.5  ...        10.0    inland        Cloudy
2             30.0        64         7.0  ...         5.5  mountain         Sunny
3             38.0        83         1.5  ...         1.0   coastal         Sunny
4             27.0        74        17.0  ...         2.5  mountain         Rainy
...            ...       ...         ...  ...         ...       ...           ...
13195         10.0        74        14.5  ...         1.0  mountain         Rainy
13196         -1.0        76         3.5  ...         6.0   coastal         Snowy
13197         30.0        77         5.5  ...         9.0   coastal        Cloudy
13198          3.0        76        10.0  ...         2.0    inland         Snowy
13199         -5.0        38         0.0  ...        10.0  mountain         Rainy

[13200 rows x 11 columns]

In [5]:
df.isna().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation           0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility              0
Location                0
Weather Type            0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Temperature           13200 non-null  float64
 1   Humidity              13200 non-null  int64  
 2   Wind Speed            13200 non-null  float64
 3   Precipitation         13200 non-null  float64
 4   Cloud Cover           13200 non-null  object 
 5   Atmospheric Pressure  13200 non-null  float64
 6   UV Index              13200 non-null  int64  
 7   Season                13200 non-null  object 
 8   Visibility            13200 non-null  float64
 9   Location              13200 non-null  object 
 10  Weather Type          13200 non-null  object 
dtypes: float64(5), int64(2), object(4)
memory usage: 1.1+ MB


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
feature = ['Cloud Cover', 'Season', 'Location']
df[feature] = df[feature].apply(le.fit_transform)
df

Temperature  Humidity  Wind Speed  ...  Visibility  Location  Weather Type
0             14.0        73         9.5  ...         3.5         1         Rainy
1             39.0        96         8.5  ...        10.0         1        Cloudy
2             30.0        64         7.0  ...         5.5         2         Sunny
3             38.0        83         1.5  ...         1.0         0         Sunny
4             27.0        74        17.0  ...         2.5         2         Rainy
...            ...       ...         ...  ...         ...       ...           ...
13195         10.0        74        14.5  ...         1.0         2         Rainy
13196         -1.0        76         3.5  ...         6.0         0         Snowy
13197         30.0        77         5.5  ...         9.0         0        Cloudy
13198          3.0        76        10.0  ...         2.0         1         Snowy
13199         -5.0        38         0.0  ...        10.0         2         Rainy

[13200 rows x 11 columns]

In [8]:
from sklearn.preprocessing import MinMaxScaler
x = df.iloc[:, :10]

scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(x)
df_scaled

array([[0.29104478, 0.59550562, 0.19587629, ..., 1.        , 0.175     ,
        0.5       ],
       [0.47761194, 0.85393258, 0.17525773, ..., 0.33333333, 0.5       ,
        0.5       ],
       [0.41044776, 0.49438202, 0.1443299 , ..., 0.33333333, 0.275     ,
        1.        ],
       ...,
       [0.41044776, 0.64044944, 0.11340206, ..., 0.        , 0.45      ,
        0.        ],
       [0.20895522, 0.62921348, 0.20618557, ..., 1.        , 0.1       ,
        0.5       ],
       [0.14925373, 0.20224719, 0.        , ..., 0.        , 0.5       ,
        1.        ]])

In [9]:
y = df['Weather Type']
y.head()

0     Rainy
1    Cloudy
2     Sunny
3     Sunny
4     Rainy
Name: Weather Type, dtype: object

In [10]:
#Membagi dataset menjadi data latih dan data uji
#dengan perbandingan 70% : 30%
from sklearn.model_selection import train_test_split

X_trainset, X_testset, y_trainset, y_testset = train_test_split(df_scaled, y, test_size=0.3, random_state=3)

print ("Ukuran X_trainset = ", X_trainset.shape)
print ("Ukuran y_trainset = ", y_trainset. shape)

print ("Ukuran X_testset = ", X_testset. shape)
print ("Ukuran y_testset = ", y_testset.shape)

Ukuran X_trainset =  (9240, 10)
Ukuran y_trainset =  (9240,)
Ukuran X_testset =  (3960, 10)
Ukuran y_testset =  (3960,)


In [11]:
#Data Classification
#Membangun model klasifikasi dengan MLP Classifier
WeatherTree = MLPClassifier(hidden_layer_sizes=(100,), activation='relu',
solver='adam', alpha=0.0001, batch_size='auto',
learning_rate='constant', learning_rate_init=0.001,
power_t=0.5, max_iter=200, shuffle=True, random_state=None,
tol=0.0001, verbose=False, warm_start=False, momentum=0.9,
nesterovs_momentum=True, early_stopping=False,
validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
epsilon=1e-08, n_iter_no_change=10, max_fun=15000)

#Melatih model dengan data latih
WeatherTree.fit(X_trainset,y_trainset)

#Memprediksi data uji dengan model
y_predWeather = WeatherTree.predict(X_testset)

#Menampilkan Label uji yang seharusnya
#dan Label hasil prediksi
result = pd. DataFrame({'True Label': y_testset, 'Predicted Label': y_predWeather})
result.head()

#Menghitung nilai akurasi prediksi model
from sklearn import metrics
print("MLP Classifier Accuracy: ", metrics.accuracy_score(y_testset, y_predWeather))

MLP Classifier Accuracy:  0.9040404040404041


c:\Users\adi\miniconda3\envs\DIP\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [12]:
#Data Classification
#Membangun model klasifikasi dengan MLP Classifier
WeatherTree = MLPClassifier(hidden_layer_sizes=(100,), activation='relu',
solver='adam', alpha=0.0001, batch_size='auto',
learning_rate='constant', learning_rate_init=0.001,
power_t=0.5, max_iter=1000, shuffle=True, random_state=None,
tol=0.0001, verbose=False, warm_start=False, momentum=0.9,
nesterovs_momentum=True, early_stopping=False,
validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
epsilon=1e-08, n_iter_no_change=10, max_fun=15000)

#Melatih model dengan data latih
WeatherTree.fit(X_trainset,y_trainset)

#Memprediksi data uji dengan model
y_predWeather = WeatherTree.predict(X_testset)

#Menampilkan Label uji yang seharusnya
#dan label hasil prediksi
result = pd.DataFrame({'True Label': y_testset, 'Predicted Label': y_predWeather})
result.head()

#Menghitung nilai akurasi prediksi model
from sklearn import metrics
print("MLP Classifier Accuracy: ", metrics.accuracy_score(y_testset, y_predWeather))

MLP Classifier Accuracy:  0.9108585858585858


In [13]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [14]:
#mengubah target label Y dari kategori
#menjadi biner
from tensorflow.keras.utils import to_categorical

encoder = LabelEncoder()
encoder.fit(y_trainset)
y_train = encoder.transform(y_trainset)
y_test = encoder.transform(y_testset)
y_train = to_categorical(y_train, num_classes=4)
y_test = to_categorical(y_test, num_classes=4)
print(y_train)
print(y_test)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [15]:
# membangun model
from keras.models import Sequential
from keras.layers import Flatten, Dense
from sklearn.metrics import confusion_matrix

model = Sequential()
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dense(4,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['acc'])

# melatih model
model.fit(X_trainset,y_train,epochs=100,batch_size=10)

# mengevaluasi model
model. summary()

loss, accuracy = model.evaluate(X_testset, y_test)
print('ANN Loss: ', loss)
print('ANN Accuracy:', accuracy)

Epoch 1/100
924/924 [==============================] - 4s 3ms/step - loss: 0.7756 - acc: 0.7631
Epoch 2/100
924/924 [==============================] - 3s 4ms/step - loss: 0.5324 - acc: 0.8450
Epoch 3/100
924/924 [==============================] - 3s 3ms/step - loss: 0.4561 - acc: 0.8668
Epoch 4/100
924/924 [==============================] - 3s 3ms/step - loss: 0.4094 - acc: 0.8767
Epoch 5/100
924/924 [==============================] - 3s 3ms/step - loss: 0.3777 - acc: 0.8850
Epoch 6/100
924/924 [==============================] - 3s 3ms/step - loss: 0.3575 - acc: 0.8871
Epoch 7/100
924/924 [==============================] - 3s 3ms/step - loss: 0.3415 - acc: 0.8924
Epoch 8/100
924/924 [==============================] - 3s 3ms/step - loss: 0.3296 - acc: 0.8944
Epoch 9/100
924/924 [==============================] - 3s 4ms/step - loss: 0.3204 - acc: 0.8940
Epoch 10/100
924/924 [==============================] - 3s 4ms/step - loss: 0.3126 - acc: 0.8981
Epoch 11/100
924/924 [=================