In [1]:
import numpy as np
import pandas as pd
import re
import nltk
from sklearn.neural_network import MLPClassifier

In [2]:
path = "..\Dataset\API_Kaggle\sentiment_analysis.csv"
corpus_df = pd.read_csv(path)
corpus_df

Year  Month  Day Time of Tweet  \
0    2018      8   18       morning   
1    2018      8   18          noon   
2    2017      8   18         night   
3    2022      6    8       morning   
4    2022      6    8          noon   
..    ...    ...  ...           ...   
494  2015     10   18         night   
495  2021      2   25       morning   
496  2022      5   30          noon   
497  2018      8   10         night   
498  2019      3   25       morning   

                                                  text sentiment     Platform  
0                What a great day!!! Looks like dream.  positive    Twitter    
1       I feel sorry, I miss you here in the sea beach  positive    Facebook   
2                                       Don't angry me  negative     Facebook  
3    We attend in the class just for listening teac...  negative    Facebook   
4                    Those who want to go, let them go  negative   Instagram   
..                                                 ...       ...          ...  
494  According to , a quarter of families under six...  negative     Twitter   
495      the plan to not spend money is not going well  negative   Instagram   
496    uploading all my bamboozle pictures of facebook   neutral    Facebook   
497   congratulations ! you guys finish a month ear...  positive     Twitter   
498   actually, I wish I was back in Tahoe.  I miss...  negative   Instagram   

[499 rows x 7 columns]

In [3]:
#Data Preprocesing
nltk.download('stopwords')
wpt = nltk.WordPunctTokenizer()
stop_words = nltk.corpus.stopwords.words('english')

def normalize_document(doc):
    #lower case and remove special characters/whitespaces
    doc = re.sub(r'[^a-zA-Z\s]','', doc, re. I|re.A)
    doc = doc. lower()
    doc = doc.strip()
    #tokenize dokumen
    tokens = wpt.tokenize(doc)
    #filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    #re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc

corpus = np.array(corpus_df['text'])
normalize_corpus = np.vectorize(normalize_document)
norm_corpus = normalize_corpus(corpus)
norm_corpus

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\adi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


array(['great day looks like dream', 'feel sorry miss sea beach',
       'dont angry',
       'attend class listening teachers reading slide nonsence',
       'want go let go', 'night feeling neutral',
       'feedings baby fun smiles coos', 'soooo high', '',
       'today first time arrive boat amazing journey',
       'love something like emc rules',
       'really really like song cardigan taylor swift',
       'sharpie running dangerously low ink',
       'want go music tonight lost voice', 'always somewhere miss',
       'dont distrube', 'dont care', 'ive sick past days',
       'im come back home past job really good time',
       'never fall love found', 'oh maya im sorry hope find soon',
       'playing kids amazing',
       'cleaning house family comming later today',
       'tried shtdown pc accenditenly click restart button really disgusting',
       'follow follow', 'amazing game playing everyday', 'im sorry',
       'im village hardly found internate feeling gloomy',
     

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vector = vectorizer.fit_transform(norm_corpus)
feature_names = vectorizer.get_feature_names_out()
dense = vector.todense()
denselist = dense.tolist()
X = pd.DataFrame(denselist, columns=feature_names)
X 

aaaaaah  aaaaaw  aawww  accenditenly  accepts  according  account  \
0        0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
1        0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
2        0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
3        0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
4        0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
..       ...     ...    ...           ...      ...        ...      ...   
494      0.0     0.0    0.0           0.0      0.0   0.421823      0.0   
495      0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
496      0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
497      0.0     0.0    0.0           0.0      0.0   0.000000      0.0   
498      0.0     0.0    0.0           0.0      0.0   0.000000      0.0   

     achievement  act  actress  ...  yesterday  yet  yor  youd  youll  youre  \
0            0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
1            0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
2            0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
3            0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
4            0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
..           ...  ...      ...  ...        ...  ...  ...   ...    ...    ...   
494          0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
495          0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
496          0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
497          0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   
498          0.0  0.0      0.0  ...        0.0  0.0  0.0   0.0    0.0    0.0   

     youtube  youve  yum  zero  
0        0.0    0.0  0.0   0.0  
1        0.0    0.0  0.0   0.0  
2        0.0    0.0  0.0   0.0  
3        0.0    0.0  0.0   0.0  
4        0.0    0.0  0.0   0.0  
..       ...    ...  ...   ...  
494      0.0    0.0  0.0   0.0  
495      0.0    0.0  0.0   0.0  
496      0.0    0.0  0.0   0.0  
497      0.0    0.0  0.0   0.0  
498      0.0    0.0  0.0   0.0  

[499 rows x 1278 columns]

In [5]:
y = corpus_df['sentiment']
y.head()

0    positive
1    positive
2    negative
3    negative
4    negative
Name: sentiment, dtype: object

In [6]:
#Membagi dataset menjadi data latih dan data uji
#dengan perbandingan 70% : 30%
from sklearn.model_selection import train_test_split

X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)

print ("Ukuran X_trainset = ", X_trainset.shape)
print ("Ukuran y_trainset = ", y_trainset. shape)

print ("Ukuran X_testset = ", X_testset. shape)
print ("Ukuran y_testset = ", y_testset.shape)

Ukuran X_trainset =  (349, 1278)
Ukuran y_trainset =  (349,)
Ukuran X_testset =  (150, 1278)
Ukuran y_testset =  (150,)


In [7]:
#Data Classification
#Membangun model klasifikasi dengan MLP Classifier
SentimentTree = MLPClassifier(hidden_layer_sizes=(100,), activation='relu',
solver='adam', alpha=0.0001, batch_size='auto',
learning_rate='constant', learning_rate_init=0.001,
power_t=0.5, max_iter=200, shuffle=True, random_state=None,
tol=0.0001, verbose=False, warm_start=False, momentum=0.9,
nesterovs_momentum=True, early_stopping=False,
validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
epsilon=1e-08, n_iter_no_change=10, max_fun=15000)

#Melatih model dengan data latih
SentimentTree.fit(X_trainset,y_trainset)

#Memprediksi data uji dengan model
y_predTree = SentimentTree.predict(X_testset)

#Menampilkan Label uji yang seharusnya
#dan label hasil prediksi
result = pd.DataFrame({'True Label': y_testset, 'Predicted Label': y_predTree})
result.head()

#Menghitung nilai akurasi prediksi model
from sklearn import metrics
print("MLP Classifier Accuracy: ", metrics.accuracy_score(y_testset, y_predTree))

MLP Classifier Accuracy:  0.66


In [8]:
#mengubah target label Y dari kategori
#menjadi numerik
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

encoder = LabelEncoder()
encoder.fit(y_trainset)
y_train = encoder.transform(y_trainset)
y_test = encoder.transform(y_testset)
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)
print(y_train)
print(y_test)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.

In [10]:
# membangun model
from keras.models import Sequential
from keras.layers import Flatten, Dense
from sklearn.metrics import confusion_matrix

model = Sequential()
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dense(3,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['acc'])

# melatih model
model.fit(X_trainset.values, y_train, epochs=100, batch_size=10)

# mengevaluasi model
model.summary()

loss, accuracy = model.evaluate(X_testset.values, y_test)
print('ANN Loss: ', loss)
print('ANN Accuracy:', accuracy)

Epoch 1/100
35/35 [==============================] - 1s 3ms/step - loss: 1.0891 - acc: 0.4155
Epoch 2/100
35/35 [==============================] - 0s 3ms/step - loss: 1.0359 - acc: 0.7536
Epoch 3/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9632 - acc: 0.8252
Epoch 4/100
35/35 [==============================] - 0s 3ms/step - loss: 0.8551 - acc: 0.8911
Epoch 5/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7126 - acc: 0.9513
Epoch 6/100
35/35 [==============================] - 0s 4ms/step - loss: 0.5543 - acc: 0.9799
Epoch 7/100
35/35 [==============================] - 0s 3ms/step - loss: 0.4099 - acc: 0.9857
Epoch 8/100
35/35 [==============================] - 0s 4ms/step - loss: 0.2969 - acc: 0.9885
Epoch 9/100
35/35 [==============================] - 0s 4ms/step - loss: 0.2186 - acc: 0.9943
Epoch 10/100
35/35 [==============================] - 0s 7ms/step - loss: 0.1641 - acc: 1.0000
Epoch 11/100
35/35 [==============================] - 0s 3m